M-181. Update the content of the shkolnikam.html page.
dev-mathematics-by/dev-mathematics-by.github.io pull request #183
Opened 2024-11-05 15:15 UTC by Kjxfub

2024-11-05 15:20 UTC, dev-mathematics-by commented on shkolnikam.html
> +		<meta name="keywords" content="Репетитор по математике с 4 по 11 класс">
meta name="keywords" - здесь должны располагаться ключевые слова. Вам должен дать их Игорь. Примеры можно посмотреть на главной странице (ключевые слова - это главные слова на конкретной странице)

2024-11-05 15:20 UTC, dev-mathematics-by requested changes
Посмотрите <meta name="keywords"

2024-11-26 14:00 UTC, dev-mathematics-by requested changes
Поменяйте ссылки на картинки (отмечены также строчки).

2025-02-06 10:42 UTC, SergeyRusetsky approved these changes
Good to go.

2025-02-06 10:44 UTC, merged