M 45 checking all properties from stylesheet in index.html
dev-mathematics-by/dev-mathematics-by.github.io pull request #46
Opened 2021-01-03 17:35 UTC by ValentinaBondarenko

M-45 remove unused style code into index.html

2021-01-07 04:48 UTC, dev-mathematics-by approved these changes
Одобрено

2021-01-10 04:46 UTC, dev-mathematics-by approved these changes
Одобрено.

2021-01-15 05:46 UTC, dev-mathematics-by requested changes
Исправить

2021-01-15 05:46 UTC, dev-mathematics-by commented on index.html
> -		<link href="style.css" rel="stylesheet" type="text/css">
Исправить.

2021-01-16 19:36 UTC, ValentinaBondarenko commented
исправлено

2021-01-19 06:16 UTC, dev-mathematics-by approved these changes
M-45 Одобрен.

2021-01-19 06:17 UTC, merged